stages:
  - build
  - test
  - deploy
build-job: 
  script: 
    - "echo \"Hello World!\""
  stage: build
  tags: 
    - ci
test-job: 
  script: 
    - "echo \"This job tests something\""
  stage: test
  tags: 
    - ssh
deploy-prod:
  stage: deploy
  script:
    - echo "This is job deploys something from the Master branch."
default:
  image: ruby:2.7.2
  
include: included.yml

useTemplate:
  image: alpine
  extends: .template