<<<<<<< HEAD
version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
=======
name: Issue Dashboard
uses: ethomson/issue-dashboard@v1.0.2

- name: WIP
  uses: wip/action@v1.1.0

   script: 
    - "echo \"Hello World!\""
>>>>>>> 939c83ac01455a3e2e5b271ce354b4478deac3fe
